<?php

return [
    'throttle' => 5,
    'admin' => 1,
    'user' => 2,
    'pagination' => 10,
    'block' => 1,
    'active' => 0,
    'memory' => [
        '8GB',
        '16GB',
        '32GB',
        '64GB',
        '128GB',
        '256GB',
        '512GB',
        '1TB',
    ],
    'color' => [
        'white',
        'pink',
        'purple',
        'red',
        'orange',
        'yellow',
        'gold',
        'green',
        'cyan',
        'blue',
        'brown',
        'grey',
        'silver',
    ],
];
